from snakemake.utils import min_version
import pandas as pd

min_version("6.10.0")


configfile: "config/config.yml"


# read sample sheet
samples = (
    pd.read_csv(config["samplesheet"], sep="\t", dtype={"sample": str})
    .set_index("sample", drop=False)
    .sort_index()
)

# ─────────────────────────────────────────────────────────────────────────────
# 1. Prep FASTQ file module
# ─────────────────────────────────────────────────────────────────────────────


# declare https://github.com/ZandvakiliLab/snakemake-prep-reads as a module
module snakemake_prep_reads:
    snakefile:
        github(
            "ZandvakiliLab/snakemake-prep-reads",
            path="workflow/Snakefile",
            branch="main",
        )
    config:
        config


# use all rules from https://github.com/ZandvakiliLab/snakemake-prep-reads
use rule * from snakemake_prep_reads as snakemake_prep_reads_*


# ─────────────────────────────────────────────────────────────────────────────
# 2. Alignment module
# ─────────────────────────────────────────────────────────────────────────────


# declare https://github.com/ZandvakiliLab/snakemake-align as a module
module snakemake_align:
    snakefile:
        github(
            "ZandvakiliLab/snakemake-align", path="workflow/Snakefile", branch="main"
        )
    config:
        config


# use all rules from https://github.com/ZandvakiliLab/snakemake-prep-reads
use rule * from snakemake_align exclude multiqc as snakemake_align_*


# ─────────────────────────────────────────────────────────────────────────────
# 3. Module rule Modification
# ─────────────────────────────────────────────────────────────────────────────


use rule get_genome from snakemake_align as snakemake_align_get_genome with:
    input:
        branch(
            lambda wc: snakemake_align.REFS[wc.ref]["source"] == "local",
            then=lambda wc: local(snakemake_align.REFS[wc.ref]["local"]["fasta"]),
            otherwise=rules.snakemake_align_ncbi_datasets.output.fasta,
        ),


use rule get_gff from snakemake_align as snakemake_align_get_gff with:
    input:
        branch(
            lambda wc: snakemake_align.REFS[wc.ref]["source"] == "local",
            then=lambda wc: local(snakemake_align.REFS[wc.ref]["local"]["gff"]),
            otherwise=rules.snakemake_align_ncbi_datasets.output.gff,
        ),


use rule star_index from snakemake_align as snakemake_align_star_index with:
    input:
        fasta="results/genome/genome.fasta",
        gtf="results/genome/genome.gff",
    threads: 8


use rule deeptools_coverage from snakemake_align as snakemake_align_deeptools_coverage with:
    params:
        effective_genome_size=lambda wc: config["mapping_stats"]["deeptools_coverage"][
            "genome_size"
        ][wc.subset],
        extra=lambda wc: (
            config["mapping_stats"]["deeptools_coverage"]["extra"]
            + " --filterRNAstrand {strand}".format(
                strand="forward" if wc.strand == "minus" else "reverse"
            )
        ),


use rule multiqc from snakemake_prep_reads as snakemake_prep_reads_multiqc with:
    input:
        lambda wc: snakemake_prep_reads.get_multiqc_input(wc)
        + snakemake_align.get_multiqc_input(wc),


# ─────────────────────────────────────────────────────────────────────────────
# 4. Default Target
# ─────────────────────────────────────────────────────────────────────────────


rule all:
    default_target: True
    input:
        "results/multiqc/multiqc_report.html",
        expand(
            "results/processed_alignment/cram/{sample}_{subset}.cram.crai",
            sample=samples.index,
            subset=list(
                config.get("mapping_postprocessing", {}).get("filter", {}).keys()
            ),
        ),
        "jbrowse/config.json",
