name: Linting

on:
  push:
    branches: [main]

jobs:
  snakemake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Linting
        uses: snakemake/snakemake-github-action@v2
        with:
          snakefile: "workflow/Snakefile"
          args: "--lint"