# .github/workflows/run_workflow.yml
name: RNA-seq Pipeline

on:
  push:
    branches: [main]
    paths:
      - 'workflow/**'
      - 'config/**'
      - 'profiles/**'
      - '.github/workflows/run_workflow.yml'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Linting
        uses: snakemake/snakemake-github-action@v2
        with:
          directory: "."
          snakefile: "workflow/Snakefile"
          args: "--lint"

  snakemake:
    # Must match the labels you set in the GARM pool
    runs-on: [self-hosted, linux, jetstream2, snakemake]

    # Optional: cancel in-progress runs on new push to same branch
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    
    needs: lint

    env:
      RESULTS_DIR: "/mnt/snakemake/"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Snakemake
        uses: snakemake/snakemake-github-action@v2
        with:
          directory: "."
          snakefile: "workflow/Snakefile"
        args: |
            --use-conda
            --use-apptainer
            --default-resources "disk_mb=25000" "tmpdir='/home/runner'"
            --resources "disk_mb=55000"
            --default-storage-provider fs
            --default-storage-prefix ${{ env.RESULTS_DIR }}
            --shared-fs-usage persistence software-deployment sources source-cache
            --local-storage-prefix /home/runner/snakemake-scratch
            --rerun-incomplete
            --cores all
            --show-failed-logs
          stagein: "mamba install -n snakemake bioconda::snakemake-storage-plugin-fs"
