# .github/workflows/run_workflow.yml
name: RNA-seq Pipeline

on:
  push:
    branches: [main]
    paths:
      - 'workflow/**'
      - 'config/**'
      - 'profiles/**'
      - '.github/workflows/run_workflow.yml'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Linting
        uses: snakemake/snakemake-github-action@v2
        with:
          directory: "."
          snakefile: "workflow/Snakefile"
          args: "--lint"

  snakemake:
    # Must match the labels you set in the GARM pool
    runs-on: [self-hosted, linux, jetstream2, snakemake]

    # Optional: cancel in-progress runs on new push to same branch
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    
    needs: lint

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare directories
        run: mkdir -p /mnt/snakemake/tmp /mnt/snakemake/snakemake-scratch
        
      - name: Run Snakemake
        uses: snakemake/snakemake-github-action@v2
        with:
          directory: "."
          snakefile: "workflow/Snakefile"
          args: "--cores all --use-conda --use-apptainer --default-resources 'tmpdir=\"/mnt/snakemake/tmp\"' --default-storage-provider fs --default-storage-prefix /mnt/snakemake --shared-fs-usage persistence software-deployment sources source-cache --local-storage-prefix /mnt/snakemake/snakemake-scratch --rerun-incomplete --show-failed-logs"
          stagein: "mamba install -n snakemake bioconda::snakemake-storage-plugin-fs"
          show-disk-usage-on-error: true